### PR TITLE
Created a input field for amount in modal #2

### PR DESCRIPTION
**Pull request by bigwampa**
re-creating for vercel

### CODE REVIEW

**Comment by bigwampa** [comment]
Input box does not accept arbitrary text input.

Please Review @Sanjeev1308

**Comment by Sanjeev1308** [comment]
> Input box does not accept arbitrary text input.
> 
> Please Review @Sanjeev1308

Fixed the issue

**Comment by bigwampa** [comment]
Deposit button now fails to open the card!

**Comment by bigwampa** [comment]
> Deposit button now fails to open the card!

Nevermind, was using the initial LP deposit button. Looks unimplemented.

**Review by Sanjeev1308 — APPROVED** [review]

**Pull request merged**
