### PR TITLE
send 3085 request after connecting

### PR DESCRIPTION
**Pull request by brendanww**
The wrong chain id dialog does not show up when connecting with Coinbase Wallet. If the cb wallet extension is set to chainId=1, then this dapp will generate transactions intended for avalanche network that have chainId=1. 

CB Wallet supports 3085 requests. This changes send a 3085 request each time a connector successfully connects to ensure the Wallet switches to the avalanche network.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Are all this package changes really necessary?

**Comment by saito-sv** [comment]
We do appreciate your contribution but for security purpose we dont allow PRs that contain changes on our packages/dependencies. We hope to add documentation in the near future about contributing

**Comment by brendanww** [comment]
@Jonasslv @saito-sv I reverted the `yarn.lock` changes; they are not necessary.

**Comment by brendanww** [comment]
@Jonasslv @saito-sv please let me know if y'all can take another look at this

**Comment by ghost** [comment]
@brendanww 

What are the steps to test it? Connect with coinbase wallet set to ETH mainnet and try to do a transaction on the page?

**Comment by brendanww** [comment]
@Jonasslv yes! the user should see a `switch ethereum chain` request as soon as they connect their wallet. It would also be great to confirm that the transaction generated has fees denominated in AVAX.

**Review by ghost — DISMISSED** [review]
LGTM

**Comment by ghost** [comment]
Just noticed that this PR is not based on DEV, LGTM but can you please rebase it against development branch?

**Review by saito-sv — APPROVED** [review]
LGTM

**Comment by ghost** [comment]
Moved commits to #369 that is based on develop

**Pull request closed without merging**
