### PR TITLE
handled partial withdraw issue

### PR DESCRIPTION
**Pull request by prodvdc**

### CODE REVIEW

**Comment by ghost** [comment]
image
this value shown in the withdraw modal should be equal as the LP quantity the user has.

**Comment by ghost** [comment]
It's not working when pools are half deposited (the user should be able to withdraw even if he didn't deposited in the gauge but only in the snowglobe).

image

**Comment by prodvdc** [comment]
> It's not working when pools are half deposited (the user should be able to withdraw even if he didn't deposited in the gauge but only in the snowglobe).
> 
> image

@Jonasslv What to show in the Available amount label if user half deposited?

**Comment by saito-sv** [comment]
@prodvdjin  there seems to be some comments on this PR, if you have addressed these review comments, please resolve the conversation.

**Comment by prodvdc** [comment]
@saito-sv I handled all comments. And I am not able to see Resolve Conversation on this PR at my side.

**Review by ghost — APPROVED** [review]
Tested and LGTM @mohsenParvar can you take a look on this PR too? You're doing a big PR that can have some conflicting stuff with it

**Pull request merged**
