### PR TITLE
added BLP (Banker Joe) icons, colors, filter option

### PR DESCRIPTION
**Pull request by prodvdc**

### CODE REVIEW

**Comment by ghost** [comment]
css is strange for this pools, breaking a line, can you look for a fix for it?
image

**Comment by prodvdc** [comment]
> css is strange for this pools, breaking a line, can you look for a fix for it? image

How can I reproduce the issue? I am not able to see such line break.

**Comment by ghost** [comment]
image
Now everything looks broken, maybe @Sanjeev1308 can take a look since he implemented the accordion

**Comment by ghost** [comment]
Same thing.
image

**Comment by ghost** [comment]
LGTM

**Review by ghost — APPROVED** [review]

**Pull request merged**
