### PR TITLE
implemented debounce on filter bar on C&E page

### PR DESCRIPTION
**Pull request by prodvdc**

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
This introduces a new bug, when you use the filter your pools order will get messed up.
image
Here I typed AVAX on the bar, removed it, and then my pools don't show at the top anymore.

**Comment by prodvdc** [comment]
It works well on local, but not working on preview server.
Let me debug and handle. Thanks for reviewing.

**Comment by prodvdc** [comment]
@Jonasslv Handled feedback from you.

**Review by ghost — APPROVED** [review]
LGTM

**Pull request merged**
