### PR TITLE
made all pools with item.symbol of AXLP link to axial

### PR DESCRIPTION
**Pull request by JoshuaLelon**
Previously, the Axial pools' "Get Token" button on the C&E page would link to Pangolin.

They now link to https://app.axial.exchange/#/pools

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1201398924627840

### CODE REVIEW

**Comment by ghost** [comment]
image
The pair AVAX-AXIAL is not provided by AXIAL but from trader joe instead, it was right before. So the idea is:
- AC4D - AM3D - AS4D should point to AXIAL.
- JLP AVAX-AXIAL should point to trader joe add liquidity interface.

**Review by prodvdc — APPROVED** [review]

**Comment by JoshuaLelon** [comment]
> image The pair AVAX-AXIAL is not provided by AXIAL but from trader joe instead, it was right before. So the idea is:
> 
>     * AC4D - AM3D - AS4D should point to AXIAL.
> 
>     * JLP AVAX-AXIAL should point to trader joe add liquidity interface.

Okay - I'm assuming that the AVAX-AXIAL pool is an exception to the rule, so that is reflected in my new commit.

It works as expected now.

**Review by ghost — CHANGES_REQUESTED** [review]
I think you can be pointing directly to the pool itself.

Something like:
https://app.axial.exchange/#/pools/{item_name}/deposit
you just need to get the name of the item var in lowercase, for example, for AM3D it should lead to this:
https://app.axial.exchange/#/pools/am3d/deposit

**Comment by JoshuaLelon** [comment]
> I think you can be pointing directly to the pool itself.
> 
> Something like: [https://app.axial.exchange/#/pools/{item_name}/deposit](https://app.axial.exchange/#/pools/%7Bitem_name%7D/deposit) you just need to get the name of the item var in lowercase, for example, for AM3D it should lead to this: https://app.axial.exchange/#/pools/am3d/deposit

Good idea! Done.

**Review by ghost — APPROVED** [review]
LGTM

**Pull request merged**
