### PR TITLE
Task/david/apy tooltip

### PR DESCRIPTION
**Pull request by prodvdc**

### CODE REVIEW

**Comment by ghost** [comment]
The rewards APR is Base APR + 10% of the Base APR, not Base APR + straight 10%.
image
image

**Comment by ghost** [comment]
Reading the Asana Task, looks like one of the tooltips is wrongly positioned.
https://app.asana.com/0/1200430190389164/1201490574984242

"The APY in the preview (unexpended card) should read "Total APY". The tooltip for it should include the following text:"

"Total APY includes the Compounded APY, which accrues in the form of LP tokens and the SNOB APR, which accrues in the form of Snowball tokens."

So the tooltip should be moved as the image:
image

**Comment by prodvdc** [comment]
@Jonasslv Handled the feedback.

**Review by ghost — APPROVED** [review]
LGTM

**Pull request merged**
