### PR TITLE
updated transaction steps according to claim reward checkbox

### PR DESCRIPTION
**Pull request by prodvdc**

### CODE REVIEW

**Comment by ghost** [comment]
This PR also needs rebasing

**Review by ghost — CHANGES_REQUESTED** [review]
image
We don't need the claim button anymore.

image
I'm getting error withdrawing.
image
This is the console log.
image
The stepbox need to be fixed.

Looks like since the zappers PR brought a lot of changes to the C&E logic this PR needs to be revisited.

**Comment by ghost** [comment]
FYI the error withdrawing happen on every pool I tested, including stablevaults

**Comment by prodvdc** [comment]
@Jonasslv I handled the feedback and pushed.

**Comment by ghost** [comment]
image
please add the option to optionally claim

**Pull request closed without merging**
